# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fire_interface_updated.ui'
#
# Created: Mon Jan 11 13:29:41 2016
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FireSDSS(object):
    def setupUi(self, FireSDSS):
        FireSDSS.setObjectName(_fromUtf8("FireSDSS"))
        FireSDSS.resize(516, 755)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.Visualisation = QtGui.QTabWidget(self.dockWidgetContents)
        self.Visualisation.setGeometry(QtCore.QRect(10, 10, 501, 701))
        self.Visualisation.setMinimumSize(QtCore.QSize(501, 701))
        self.Visualisation.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Visualisation.setMouseTracking(True)
        self.Visualisation.setObjectName(_fromUtf8("Visualisation"))
        self.generaltab = QtGui.QWidget()
        self.generaltab.setWhatsThis(_fromUtf8(""))
        self.generaltab.setAccessibleName(_fromUtf8(""))
        self.generaltab.setObjectName(_fromUtf8("generaltab"))
        self.firelocationbutton = QtGui.QPushButton(self.generaltab)
        self.firelocationbutton.setGeometry(QtCore.QRect(110, 120, 241, 111))
        self.firelocationbutton.setMinimumSize(QtCore.QSize(241, 111))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.firelocationbutton.setFont(font)
        self.firelocationbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.firelocationbutton.setMouseTracking(True)
        self.firelocationbutton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.firelocationbutton.setAutoFillBackground(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../interface/FIRE.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.firelocationbutton.setIcon(icon)
        self.firelocationbutton.setIconSize(QtCore.QSize(100, 100))
        self.firelocationbutton.setObjectName(_fromUtf8("firelocationbutton"))
        self.chooseservicelabel = QtGui.QLabel(self.generaltab)
        self.chooseservicelabel.setGeometry(QtCore.QRect(40, 280, 251, 41))
        self.chooseservicelabel.setMinimumSize(QtCore.QSize(251, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.chooseservicelabel.setFont(font)
        self.chooseservicelabel.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.chooseservicelabel.setMouseTracking(True)
        self.chooseservicelabel.setObjectName(_fromUtf8("chooseservicelabel"))
        self.policebutton = QtGui.QPushButton(self.generaltab)
        self.policebutton.setGeometry(QtCore.QRect(30, 350, 121, 101))
        self.policebutton.setMinimumSize(QtCore.QSize(121, 101))
        self.policebutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.policebutton.setMouseTracking(True)
        self.policebutton.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../interface/police-car2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.policebutton.setIcon(icon1)
        self.policebutton.setIconSize(QtCore.QSize(130, 130))
        self.policebutton.setObjectName(_fromUtf8("policebutton"))
        self.firetruckbutton = QtGui.QPushButton(self.generaltab)
        self.firetruckbutton.setGeometry(QtCore.QRect(170, 350, 121, 101))
        self.firetruckbutton.setMinimumSize(QtCore.QSize(121, 101))
        self.firetruckbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.firetruckbutton.setMouseTracking(True)
        self.firetruckbutton.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("../interface/1.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.firetruckbutton.setIcon(icon2)
        self.firetruckbutton.setIconSize(QtCore.QSize(100, 120))
        self.firetruckbutton.setObjectName(_fromUtf8("firetruckbutton"))
        self.ambulancebutton = QtGui.QPushButton(self.generaltab)
        self.ambulancebutton.setGeometry(QtCore.QRect(310, 350, 121, 101))
        self.ambulancebutton.setMinimumSize(QtCore.QSize(121, 101))
        self.ambulancebutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ambulancebutton.setMouseTracking(True)
        self.ambulancebutton.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("../interface/images.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ambulancebutton.setIcon(icon3)
        self.ambulancebutton.setIconSize(QtCore.QSize(110, 110))
        self.ambulancebutton.setObjectName(_fromUtf8("ambulancebutton"))
        self.generalline = QtGui.QFrame(self.generaltab)
        self.generalline.setGeometry(QtCore.QRect(10, 250, 471, 16))
        self.generalline.setMinimumSize(QtCore.QSize(471, 16))
        self.generalline.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.generalline.setMouseTracking(True)
        self.generalline.setFrameShape(QtGui.QFrame.HLine)
        self.generalline.setFrameShadow(QtGui.QFrame.Sunken)
        self.generalline.setObjectName(_fromUtf8("generalline"))
        self.firelabel_2 = QtGui.QLabel(self.generaltab)
        self.firelabel_2.setGeometry(QtCore.QRect(110, 30, 360, 71))
        self.firelabel_2.setMinimumSize(QtCore.QSize(360, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.firelabel_2.setFont(font)
        self.firelabel_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.firelabel_2.setMouseTracking(True)
        self.firelabel_2.setTextFormat(QtCore.Qt.PlainText)
        self.firelabel_2.setObjectName(_fromUtf8("firelabel_2"))
        self.Visualisation.addTab(self.generaltab, _fromUtf8(""))
        self.datatab = QtGui.QWidget()
        self.datatab.setObjectName(_fromUtf8("datatab"))
        self.selectlayerlabel = QtGui.QLabel(self.datatab)
        self.selectlayerlabel.setGeometry(QtCore.QRect(20, 30, 181, 31))
        self.selectlayerlabel.setMinimumSize(QtCore.QSize(181, 31))
        self.selectlayerlabel.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.selectlayerlabel.setMouseTracking(True)
        self.selectlayerlabel.setObjectName(_fromUtf8("selectlayerlabel"))
        self.selectlayercombo = QtGui.QComboBox(self.datatab)
        self.selectlayercombo.setGeometry(QtCore.QRect(200, 30, 231, 31))
        self.selectlayercombo.setMinimumSize(QtCore.QSize(231, 31))
        self.selectlayercombo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.selectlayercombo.setMouseTracking(True)
        self.selectlayercombo.setObjectName(_fromUtf8("selectlayercombo"))
        self.locatefireline = QtGui.QFrame(self.datatab)
        self.locatefireline.setGeometry(QtCore.QRect(0, 200, 481, 20))
        self.locatefireline.setMinimumSize(QtCore.QSize(481, 20))
        self.locatefireline.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.locatefireline.setFrameShape(QtGui.QFrame.HLine)
        self.locatefireline.setFrameShadow(QtGui.QFrame.Sunken)
        self.locatefireline.setObjectName(_fromUtf8("locatefireline"))
        self.label_6 = QtGui.QLabel(self.datatab)
        self.label_6.setGeometry(QtCore.QRect(20, 150, 181, 31))
        self.label_6.setMinimumSize(QtCore.QSize(181, 31))
        self.label_6.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_6.setMouseTracking(True)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.clearlayercombo = QtGui.QComboBox(self.datatab)
        self.clearlayercombo.setGeometry(QtCore.QRect(200, 150, 231, 31))
        self.clearlayercombo.setMinimumSize(QtCore.QSize(231, 31))
        self.clearlayercombo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.clearlayercombo.setMouseTracking(True)
        self.clearlayercombo.setObjectName(_fromUtf8("clearlayercombo"))
        self.Visualisation.addTab(self.datatab, _fromUtf8(""))
        self.analysistab = QtGui.QWidget()
        self.analysistab.setStyleSheet(_fromUtf8(""))
        self.analysistab.setObjectName(_fromUtf8("analysistab"))
        self.hydrantsbutton = QtGui.QPushButton(self.analysistab)
        self.hydrantsbutton.setGeometry(QtCore.QRect(30, 220, 141, 121))
        self.hydrantsbutton.setMinimumSize(QtCore.QSize(141, 121))
        self.hydrantsbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.hydrantsbutton.setMouseTracking(True)
        self.hydrantsbutton.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("../interface/hydrantsicon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.hydrantsbutton.setIcon(icon4)
        self.hydrantsbutton.setIconSize(QtCore.QSize(120, 120))
        self.hydrantsbutton.setObjectName(_fromUtf8("hydrantsbutton"))
        self.shortestroutebutton = QtGui.QPushButton(self.analysistab)
        self.shortestroutebutton.setGeometry(QtCore.QRect(40, 20, 161, 41))
        self.shortestroutebutton.setMinimumSize(QtCore.QSize(161, 41))
        self.shortestroutebutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.shortestroutebutton.setMouseTracking(True)
        self.shortestroutebutton.setObjectName(_fromUtf8("shortestroutebutton"))
        self.cheanroutebutton = QtGui.QPushButton(self.analysistab)
        self.cheanroutebutton.setGeometry(QtCore.QRect(250, 20, 171, 41))
        self.cheanroutebutton.setMinimumSize(QtCore.QSize(171, 41))
        self.cheanroutebutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cheanroutebutton.setMouseTracking(True)
        self.cheanroutebutton.setObjectName(_fromUtf8("cheanroutebutton"))
        self.smokebufferbutton = QtGui.QPushButton(self.analysistab)
        self.smokebufferbutton.setGeometry(QtCore.QRect(30, 380, 141, 111))
        self.smokebufferbutton.setMinimumSize(QtCore.QSize(141, 111))
        self.smokebufferbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.smokebufferbutton.setMouseTracking(True)
        self.smokebufferbutton.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("../interface/Transparent_Smoke_Clipart_PNG_Image.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.smokebufferbutton.setIcon(icon5)
        self.smokebufferbutton.setIconSize(QtCore.QSize(120, 120))
        self.smokebufferbutton.setObjectName(_fromUtf8("smokebufferbutton"))
        self.buildingbutton = QtGui.QPushButton(self.analysistab)
        self.buildingbutton.setGeometry(QtCore.QRect(30, 520, 141, 111))
        self.buildingbutton.setMinimumSize(QtCore.QSize(141, 111))
        self.buildingbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buildingbutton.setMouseTracking(True)
        self.buildingbutton.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("../interface/building-20clip-20art-12065771771975582164reporter_flat.svg.med.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buildingbutton.setIcon(icon6)
        self.buildingbutton.setIconSize(QtCore.QSize(150, 100))
        self.buildingbutton.setObjectName(_fromUtf8("buildingbutton"))
        self.buildingupdate = QtGui.QPushButton(self.analysistab)
        self.buildingupdate.setGeometry(QtCore.QRect(210, 550, 251, 51))
        self.buildingupdate.setMinimumSize(QtCore.QSize(251, 41))
        self.buildingupdate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buildingupdate.setMouseTracking(True)
        self.buildingupdate.setObjectName(_fromUtf8("buildingupdate"))
        self.analysisline1 = QtGui.QFrame(self.analysistab)
        self.analysisline1.setGeometry(QtCore.QRect(-10, 160, 521, 16))
        self.analysisline1.setMinimumSize(QtCore.QSize(521, 16))
        self.analysisline1.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.analysisline1.setMouseTracking(True)
        self.analysisline1.setFrameShape(QtGui.QFrame.HLine)
        self.analysisline1.setFrameShadow(QtGui.QFrame.Sunken)
        self.analysisline1.setObjectName(_fromUtf8("analysisline1"))
        self.getwatersourcelabel = QtGui.QLabel(self.analysistab)
        self.getwatersourcelabel.setGeometry(QtCore.QRect(30, 340, 151, 21))
        self.getwatersourcelabel.setMinimumSize(QtCore.QSize(151, 21))
        self.getwatersourcelabel.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.getwatersourcelabel.setMouseTracking(True)
        self.getwatersourcelabel.setObjectName(_fromUtf8("getwatersourcelabel"))
        self.buildingindangerlable = QtGui.QLabel(self.analysistab)
        self.buildingindangerlable.setGeometry(QtCore.QRect(30, 630, 171, 21))
        self.buildingindangerlable.setMinimumSize(QtCore.QSize(171, 21))
        self.buildingindangerlable.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.buildingindangerlable.setMouseTracking(True)
        self.buildingindangerlable.setObjectName(_fromUtf8("buildingindangerlable"))
        self.cleanwatersourcebutton = QtGui.QPushButton(self.analysistab)
        self.cleanwatersourcebutton.setGeometry(QtCore.QRect(260, 220, 141, 121))
        self.cleanwatersourcebutton.setMinimumSize(QtCore.QSize(141, 121))
        self.cleanwatersourcebutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cleanwatersourcebutton.setMouseTracking(True)
        self.cleanwatersourcebutton.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("../interface/hydrantsicon2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cleanwatersourcebutton.setIcon(icon7)
        self.cleanwatersourcebutton.setIconSize(QtCore.QSize(100, 100))
        self.cleanwatersourcebutton.setObjectName(_fromUtf8("cleanwatersourcebutton"))
        self.analysisline2 = QtGui.QFrame(self.analysistab)
        self.analysisline2.setGeometry(QtCore.QRect(-20, 360, 531, 16))
        self.analysisline2.setMinimumSize(QtCore.QSize(531, 16))
        self.analysisline2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.analysisline2.setMouseTracking(True)
        self.analysisline2.setFrameShape(QtGui.QFrame.HLine)
        self.analysisline2.setFrameShadow(QtGui.QFrame.Sunken)
        self.analysisline2.setObjectName(_fromUtf8("analysisline2"))
        self.label_4 = QtGui.QLabel(self.analysistab)
        self.label_4.setGeometry(QtCore.QRect(260, 340, 161, 21))
        self.label_4.setMinimumSize(QtCore.QSize(161, 21))
        self.label_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_4.setMouseTracking(True)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.analysistab)
        self.label_5.setGeometry(QtCore.QRect(30, 490, 71, 21))
        self.label_5.setMinimumSize(QtCore.QSize(71, 21))
        self.label_5.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_5.setMouseTracking(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.bufferCutoffEdit = QtGui.QLineEdit(self.analysistab)
        self.bufferCutoffEdit.setGeometry(QtCore.QRect(310, 180, 61, 21))
        self.bufferCutoffEdit.setMinimumSize(QtCore.QSize(20, 21))
        self.bufferCutoffEdit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.bufferCutoffEdit.setMouseTracking(True)
        self.bufferCutoffEdit.setObjectName(_fromUtf8("bufferCutoffEdit"))
        self.getwatersourcelabel_2 = QtGui.QLabel(self.analysistab)
        self.getwatersourcelabel_2.setGeometry(QtCore.QRect(30, 180, 271, 21))
        self.getwatersourcelabel_2.setMinimumSize(QtCore.QSize(100, 21))
        self.getwatersourcelabel_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.getwatersourcelabel_2.setMouseTracking(True)
        self.getwatersourcelabel_2.setObjectName(_fromUtf8("getwatersourcelabel_2"))
        self.reportList1 = QtGui.QListWidget(self.analysistab)
        self.reportList1.setGeometry(QtCore.QRect(40, 70, 381, 81))
        self.reportList1.setMinimumSize(QtCore.QSize(231, 81))
        self.reportList1.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.reportList1.setMouseTracking(True)
        self.reportList1.setObjectName(_fromUtf8("reportList1"))
        self.label_25 = QtGui.QLabel(self.analysistab)
        self.label_25.setGeometry(QtCore.QRect(230, 380, 301, 111))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_14 = QtGui.QLabel(self.analysistab)
        self.label_14.setGeometry(QtCore.QRect(390, 180, 41, 21))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.Visualisation.addTab(self.analysistab, _fromUtf8(""))
        self.visualizationtab = QtGui.QWidget()
        self.visualizationtab.setObjectName(_fromUtf8("visualizationtab"))
        self.line = QtGui.QFrame(self.visualizationtab)
        self.line.setGeometry(QtCore.QRect(0, 470, 491, 20))
        self.line.setMinimumSize(QtCore.QSize(491, 20))
        self.line.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.line.setMouseTracking(True)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.visualizationtab)
        self.line_2.setGeometry(QtCore.QRect(0, 260, 491, 20))
        self.line_2.setMinimumSize(QtCore.QSize(491, 20))
        self.line_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.line_2.setMouseTracking(True)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label_9 = QtGui.QLabel(self.visualizationtab)
        self.label_9.setGeometry(QtCore.QRect(250, 520, 241, 31))
        self.label_9.setMinimumSize(QtCore.QSize(151, 21))
        self.label_9.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_9.setMouseTracking(True)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.frame = QtGui.QFrame(self.visualizationtab)
        self.frame.setGeometry(QtCore.QRect(20, 80, 461, 171))
        self.frame.setMinimumSize(QtCore.QSize(461, 141))
        self.frame.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.frame.setMouseTracking(True)
        self.frame.setFocusPolicy(QtCore.Qt.NoFocus)
        self.frame.setFrameShape(QtGui.QFrame.Panel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.reportList_3 = QtGui.QListWidget(self.frame)
        self.reportList_3.setEnabled(True)
        self.reportList_3.setGeometry(QtCore.QRect(10, 20, 111, 31))
        self.reportList_3.setMinimumSize(QtCore.QSize(111, 31))
        self.reportList_3.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.reportList_3.setMouseTracking(True)
        self.reportList_3.setViewMode(QtGui.QListView.ListMode)
        self.reportList_3.setObjectName(_fromUtf8("reportList_3"))
        self.reportList_4 = QtGui.QListWidget(self.frame)
        self.reportList_4.setGeometry(QtCore.QRect(10, 120, 111, 31))
        self.reportList_4.setMinimumSize(QtCore.QSize(111, 31))
        self.reportList_4.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.reportList_4.setMouseTracking(True)
        self.reportList_4.setViewMode(QtGui.QListView.ListMode)
        self.reportList_4.setObjectName(_fromUtf8("reportList_4"))
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(170, 20, 251, 21))
        self.label_3.setMinimumSize(QtCore.QSize(181, 21))
        self.label_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_3.setMouseTracking(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.reportList_11 = QtGui.QListWidget(self.frame)
        self.reportList_11.setGeometry(QtCore.QRect(10, 70, 111, 31))
        self.reportList_11.setMinimumSize(QtCore.QSize(111, 31))
        self.reportList_11.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.reportList_11.setMouseTracking(True)
        self.reportList_11.setViewMode(QtGui.QListView.ListMode)
        self.reportList_11.setObjectName(_fromUtf8("reportList_11"))
        self.label_13 = QtGui.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(170, 70, 281, 31))
        self.label_13.setMinimumSize(QtCore.QSize(261, 21))
        self.label_13.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_13.setMouseTracking(True)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(170, 130, 261, 21))
        self.label_8.setMinimumSize(QtCore.QSize(181, 21))
        self.label_8.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_8.setMouseTracking(True)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.frame_2 = QtGui.QFrame(self.visualizationtab)
        self.frame_2.setGeometry(QtCore.QRect(20, 290, 461, 171))
        self.frame_2.setMinimumSize(QtCore.QSize(451, 141))
        self.frame_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.frame_2.setMouseTracking(True)
        self.frame_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.frame_2.setFrameShape(QtGui.QFrame.Panel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.reportList_7 = QtGui.QListWidget(self.frame_2)
        self.reportList_7.setGeometry(QtCore.QRect(20, 120, 91, 31))
        self.reportList_7.setMinimumSize(QtCore.QSize(91, 31))
        self.reportList_7.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.reportList_7.setMouseTracking(True)
        self.reportList_7.setViewMode(QtGui.QListView.ListMode)
        self.reportList_7.setObjectName(_fromUtf8("reportList_7"))
        self.reportList_6 = QtGui.QListWidget(self.frame_2)
        self.reportList_6.setGeometry(QtCore.QRect(20, 70, 91, 31))
        self.reportList_6.setMinimumSize(QtCore.QSize(91, 31))
        self.reportList_6.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.reportList_6.setMouseTracking(True)
        self.reportList_6.setViewMode(QtGui.QListView.ListMode)
        self.reportList_6.setObjectName(_fromUtf8("reportList_6"))
        self.label_11 = QtGui.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(160, 120, 291, 31))
        self.label_11.setMinimumSize(QtCore.QSize(241, 21))
        self.label_11.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_11.setMouseTracking(True)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label = QtGui.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(160, 20, 301, 31))
        self.label.setMinimumSize(QtCore.QSize(221, 21))
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label.setMouseTracking(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_7 = QtGui.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(160, 70, 311, 31))
        self.label_7.setMinimumSize(QtCore.QSize(231, 21))
        self.label_7.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_7.setMouseTracking(True)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.reportList_5 = QtGui.QListWidget(self.frame_2)
        self.reportList_5.setGeometry(QtCore.QRect(20, 20, 91, 31))
        self.reportList_5.setMinimumSize(QtCore.QSize(91, 31))
        self.reportList_5.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.reportList_5.setMouseTracking(True)
        self.reportList_5.setViewMode(QtGui.QListView.ListMode)
        self.reportList_5.setObjectName(_fromUtf8("reportList_5"))
        self.frame_3 = QtGui.QFrame(self.visualizationtab)
        self.frame_3.setGeometry(QtCore.QRect(20, 500, 461, 121))
        self.frame_3.setMinimumSize(QtCore.QSize(441, 101))
        self.frame_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.frame_3.setMouseTracking(True)
        self.frame_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.frame_3.setFrameShape(QtGui.QFrame.Panel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.reportList_9 = QtGui.QListWidget(self.frame_3)
        self.reportList_9.setGeometry(QtCore.QRect(30, 150, 71, 31))
        self.reportList_9.setMinimumSize(QtCore.QSize(71, 31))
        self.reportList_9.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.reportList_9.setMouseTracking(True)
        self.reportList_9.setObjectName(_fromUtf8("reportList_9"))
        self.reportList_8 = QtGui.QListWidget(self.frame_3)
        self.reportList_8.setGeometry(QtCore.QRect(20, 20, 171, 31))
        self.reportList_8.setMinimumSize(QtCore.QSize(171, 31))
        self.reportList_8.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.reportList_8.setMouseTracking(True)
        self.reportList_8.setAcceptDrops(False)
        self.reportList_8.setToolTip(_fromUtf8(""))
        self.reportList_8.setStatusTip(_fromUtf8(""))
        self.reportList_8.setWhatsThis(_fromUtf8(""))
        self.reportList_8.setViewMode(QtGui.QListView.ListMode)
        self.reportList_8.setObjectName(_fromUtf8("reportList_8"))
        self.reportList_10 = QtGui.QListWidget(self.frame_3)
        self.reportList_10.setGeometry(QtCore.QRect(20, 70, 171, 31))
        self.reportList_10.setMinimumSize(QtCore.QSize(171, 31))
        self.reportList_10.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.reportList_10.setMouseTracking(True)
        self.reportList_10.setViewMode(QtGui.QListView.ListMode)
        self.reportList_10.setObjectName(_fromUtf8("reportList_10"))
        self.label_2 = QtGui.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(230, 70, 201, 31))
        self.label_2.setMinimumSize(QtCore.QSize(201, 21))
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_2.setMouseTracking(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.showinfo = QtGui.QPushButton(self.visualizationtab)
        self.showinfo.setGeometry(QtCore.QRect(90, 10, 311, 51))
        self.showinfo.setMinimumSize(QtCore.QSize(311, 51))
        self.showinfo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.showinfo.setMouseTracking(True)
        self.showinfo.setObjectName(_fromUtf8("showinfo"))
        self.Visualisation.addTab(self.visualizationtab, _fromUtf8(""))
        self.reporting = QtGui.QWidget()
        self.reporting.setObjectName(_fromUtf8("reporting"))
        self.savemapbutton = QtGui.QPushButton(self.reporting)
        self.savemapbutton.setGeometry(QtCore.QRect(230, 40, 141, 41))
        self.savemapbutton.setMinimumSize(QtCore.QSize(141, 41))
        self.savemapbutton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.savemapbutton.setMouseTracking(True)
        self.savemapbutton.setObjectName(_fromUtf8("savemapbutton"))
        self.label_10 = QtGui.QLabel(self.reporting)
        self.label_10.setGeometry(QtCore.QRect(20, 40, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setUnderline(True)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_12 = QtGui.QLabel(self.reporting)
        self.label_12.setGeometry(QtCore.QRect(20, 100, 461, 71))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.Visualisation.addTab(self.reporting, _fromUtf8(""))
        FireSDSS.setWidget(self.dockWidgetContents)

        self.retranslateUi(FireSDSS)
        self.Visualisation.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FireSDSS)

    def retranslateUi(self, FireSDSS):
        FireSDSS.setWindowTitle(_translate("FireSDSS", "FireSDSS", None))
        self.firelocationbutton.setText(_translate("FireSDSS", "    Fire Location", None))
        self.chooseservicelabel.setText(_translate("FireSDSS", "Choose Service:", None))
        self.firelabel_2.setText(_translate("FireSDSS", "COMMAND AND CONTROL SYSTEM\n"
"          FIRE", None))
        self.Visualisation.setTabText(self.Visualisation.indexOf(self.generaltab), _translate("FireSDSS", "General", None))
        self.selectlayerlabel.setText(_translate("FireSDSS", "Show selected Layer:", None))
        self.label_6.setText(_translate("FireSDSS", "Clear selected layer:", None))
        self.Visualisation.setTabText(self.Visualisation.indexOf(self.datatab), _translate("FireSDSS", "Data", None))
        self.analysistab.setToolTip(_translate("FireSDSS", "<html><head/><body><p><br/></p></body></html>", None))
        self.shortestroutebutton.setText(_translate("FireSDSS", "Shortest Route", None))
        self.cheanroutebutton.setText(_translate("FireSDSS", "Clean Route", None))
        self.buildingupdate.setText(_translate("FireSDSS", "Update Threatened Area", None))
        self.getwatersourcelabel.setText(_translate("FireSDSS", "Get Water Sources", None))
        self.buildingindangerlable.setText(_translate("FireSDSS", "Get Threatened Area", None))
        self.label_4.setText(_translate("FireSDSS", "Clean Water Sources", None))
        self.label_5.setText(_translate("FireSDSS", "Get Smoke", None))
        self.bufferCutoffEdit.setText(_translate("FireSDSS", "100", None))
        self.getwatersourcelabel_2.setText(_translate("FireSDSS", "Define the Buffer for Hydrants:", None))
        self.label_25.setText(_translate("FireSDSS", "Download Time Manager\n"
"\n"
"Push the Play Button\n"
"\n"
"Check the Different Threatened\n"
"Area During Time", None))
        self.label_14.setText(_translate("FireSDSS", "m", None))
        self.Visualisation.setTabText(self.Visualisation.indexOf(self.analysistab), _translate("FireSDSS", "Analysis", None))
        self.label_9.setText(_translate("FireSDSS", "Start of the Fire", None))
        self.label_3.setText(_translate("FireSDSS", "Affected Building(s)", None))
        self.label_13.setText(_translate("FireSDSS", "Type of the Affected Building(s)", None))
        self.label_8.setText(_translate("FireSDSS", "Affected Population", None))
        self.label_11.setText(_translate("FireSDSS", "Threatened Population (Night)", None))
        self.label.setText(_translate("FireSDSS", "Threatened Building(s)", None))
        self.label_7.setText(_translate("FireSDSS", "Threatened Population (Day)", None))
        self.label_2.setText(_translate("FireSDSS", "End of the Fire", None))
        self.showinfo.setText(_translate("FireSDSS", "Show Information about the Event", None))
        self.Visualisation.setTabText(self.Visualisation.indexOf(self.visualizationtab), _translate("FireSDSS", "Reporting", None))
        self.savemapbutton.setText(_translate("FireSDSS", "Save map", None))
        self.label_10.setText(_translate("FireSDSS", "Save map as image:", None))
        self.label_12.setText(_translate("FireSDSS", "The map is saved under the Project folder.", None))
        self.Visualisation.setTabText(self.Visualisation.indexOf(self.reporting), _translate("FireSDSS", "Save", None))

